server {
    listen 83;
    listen [::]:83;

    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass toskos_app:9001;
    }

    location ~ /\.ht {
        deny all;
    }
}